name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push if updated
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "updated snake animation" || echo "No changes to commit"
          git push

      - name: Upload to repository
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg

